name: Install Workflow

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
      - name: make directory
        run: mkdir - p actions/workflow

      - name: list
        run: ls actions 
