name: Nginx Version Check Workflow

on:
  push:
    branches:
      - main

jobs:
  install_nginx:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Nginx version
        run: sudo apt install plocate -y 

      - name: echo 
        run: echo "Hello World"
