name: Nginx Version Check Workflow

on:
  push:
    branches:
      - main

jobs:
  install_nginx:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Nginx version
        run: sudo apt install plocate -y 
